name: Lighthouse CI
on: [pull_request]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Branch name
        run: echo running on branch ${{ steps.branch-name.outputs.current_branch }}
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://${{ steps.branch-name.outputs.current_branch }}--helix-project-boilerplate--dylandepass.hlx.live/
          runs: 5
          configPath: ../lighthouse/lighthouserc.json
          uploadArtifacts: true # save results as an action artifacts
          serverBaseUrl: ${{ secrets.LHCI_SERVER_BASE_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}